language: cpp

sudo: false
env:
  - JIT_OPTS='--opt=jit' TARGET_OPTS='target.py'
  - JIT_OPTS='' TARGET_OPTS='target.py'

matrix:
  fast_finish: true

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - make PYTHON=python build
  - make compile_src
  - make compile_tests
  - make run_built_tests

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libffi-dev
    - libedit-dev
    - libboost-all-dev
    - zlib1g-dev
    - zlib-bin
    - gcc-4.8
    - g++-4.8

notifications:
  irc: "chat.freenode.net#pixie-lang"
